version: "3"
services:
  api:
    # image: node:14-alpine
    build: .
    container_name: "api"
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/todo?schema=public
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app:ro
      - ./node_modules
    command: "npm start"
  db:
    image: postgres:11.4-alpine
    container_name: "db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
    driver: local

    
