version: "3"
services:
  db:
    env_file:
      - .env.test
    image: postgres:11.4-alpine
    container_name: "db-test"
    ports:
      - 9999:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
